language: node_js
services: 
  - mongodb
node_js:
  - node
before_script:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run test
deploy:
  provider: lambda
  function_name: persona
  region: 'us-east-1'
  runtime: nodejs12.x
  edge: true
  on:
    branch:
      - main